name: mushaf_practice
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  get: ^4.7.2
  path:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/meta/
    - assets/mushaf/
    - assets/script/

  fonts:
    # Primary Quran text fonts (similar styles)
    - family: Hafs
      fonts:
        - asset: assets/fonts/Hafs.ttf
    - family: UthmanicHafs_V22
      fonts:
        - asset: assets/fonts/UthmanicHafs_V22.ttf
    - family: me_quran_volt_newmet
      fonts:
        - asset: assets/fonts/me_quran_volt_newmet.ttf

    # Secondary fallbacks (still Arabic calligraphy)
    - family: KFGQPCNastaleeq
      fonts:
        - asset: assets/fonts/KFGQPCNastaleeq-Regular.ttf
    - family: DigitalKhattV2
      fonts:
        - asset: assets/fonts/DigitalKhattV2.otf

    # Keep only if you need headers/names (remove if not used)
    - family: QCF_SurahHeader
      fonts:
        - asset: assets/fonts/QCF_SurahHeader_COLOR-Regular.ttf
    - family: SurahName
      fonts:
        - asset: assets/fonts/surah-name-v2.ttf

# REMOVE THESE FONTS (commented out):
# Nabi.ttf - completely different style
# surah_names.ttf - duplicate of surah names