name: mushaf_practice
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  get: ^4.7.2
  path:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/meta/
    - assets/mushaf/
    - assets/script/

  fonts:
    # Only two fonts - keep it simple
    - family: Me
      fonts:
        - asset: assets/fonts/me_quran_volt_newmet.ttf

    - family: Uthmani
      fonts:
        - asset: assets/fonts/UthmanicHafs_V22.ttf